spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql://localhost:3306/smarthr_job?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.smarthr.job.model
  configuration:
    map-underscore-to-camel-case: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000